/**
 * Root Layout
 *
 * This file defines the global layout for the entire application.
 * It loads global styles, fonts, providers, and UI utilities
 * that should be available on every page.
 *
 * Purpose:
 * - Apply global CSS and fonts
 * - Wrap the app with tRPC provider (
 *  Benefit:
 * - Enables type-safe API calls everywhere in the app
 * - Shares a single tRPC/React Query client
 * - Avoids setting up tRPC context in every page or component
 * )
 * - Mount global UI components like toast notifications
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root application layout that applies global fonts, wraps content with the tRPC provider, and mounts a global toaster.
 *
 * @param children - The page content to render inside the layout.
 * @returns The root HTML structure containing `children` wrapped by `TRPCReactProvider` with a mounted `Toaster`.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCReactProvider>
          {children}
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}